const MIN_BALL_SIZE = 15;
const MAX_BALL_SIZE = 20;
const MIN_X_BOUNDARY = 0;
const MAX_X_BOUNDARY = 1800;
const MIN_Y_BOUNDARY = 0;
const MAX_Y_BOUNDARY = 900;
const MIN_VELOCITY = -5;
const MAX_VELOCITY = 5;